---
title: "Eleitorado"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library("dplyr")
library("lubridate")
```

```{r init}
baseEleleitorado <- read.csv2("eleitorado.csv",fileEncoding = "UTF-8")
baseVotacao  <- read.csv2("votacao.csv",fileEncoding = "UTF-8")
```

## Quantos eleitores havia no Brasil em 2016?
```{r}
sum(baseEleleitorado$ELEITORADO.APTO)
```
## Quantos eleitores por sexo havia no Brasil em 2016?
```{r}
paste("FEMININO: ", sum(baseEleleitorado$FEMININO))
paste("MASCULINO: ", sum(baseEleleitorado$MASCULINO))
```
## Quais estados têm mais eleitores com menos que 35 anos do que com mais que 25 havia no Brasil em 2016?
```{r}
baseEleleitorado %>% 
  mutate(MENOR_QUE_35 = rowSums(select(.,X16.ANOS : X25.A.34.ANOS)),
         MAIOR_QUE_35 = rowSums(select(.,X35.A.44.ANOS : SUPERIOR.A.79.ANOS))) %>%
  filter(MENOR_QUE_35 > MAIOR_QUE_35) %>%
  group_by(UF) %>%
  distinct(UF)

```

## Quantos votos nominais cada partido teve?

```{r}
baseVotacao %>% 
  group_by(SIGLA_PARTIDO) %>%
  summarise(TOTAL = sum(QTDE_VOTOS_NOMINAIS, na.rm = TRUE)) %>% 
  arrange(desc(TOTAL))

```


## Quantos votos nominais o DEM (Democratas) teve em Roraima?

```{r}
baseVotacao %>% 
  filter(SIGLA_UF == "RO", SIGLA_PARTIDO == "DEM") %>%
  summarise(TOTAL = sum(QTDE_VOTOS_NOMINAIS, na.rm = TRUE))

```



