---
title: "Factors"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(forcats)
library(dplyr)
library(ggplot2)
```

## Fatores

http://material.curso-r.com/forcats/

```{r}
d <- restaurantes_pressao <- read_delim("restaurantes_pressao.csv", 
    ";", escape_double = FALSE, col_names = c("voluntario", "restaurante", "pressao"), 
    trim_ws = TRUE)

```

###Sem fatores

```{r}
d %>% 
ggplot(aes(x = restaurante, y = pressao)) +
  geom_point() + 
  theme_bw(15)

```

###Com fatores

```{r}
d %>% 
mutate(restaurante = factor(restaurante, levels = c("Frutaria da vila", "Outlet", "Max Donalds"))) %>% 
ggplot(aes(x = restaurante, y = pressao)) +
  geom_point() + 
  theme_bw(15)
```

###package forcats
```{r}
fator_1 <- factor(c("a","b","c"))
fator_2 <- factor(c("d","e"))

fator_3_sem_sentido <- c(fator_1, fator_2)
fator_3_sem_sentido


fator_3_com_sentido <- forcats::fct_c(fator_1, fator_2)
fator_3_com_sentido

fator <- factor(c("a","b","c"))
fator
novos_niveis <- c("c", "b", "a")
  
fator <- forcats::lvls_revalue(fator, novos_niveis)
fator

fator <- factor(c("a","a","a","b","b", "c", "d", "e"))

fct_collapse(fator, b2 = c("b", "c"), a2 = c("a", "d"))
fct_recode(fator, b2 = "b", b2 = "c", a2 = "a", a2 = "d")

fct_lump(fator, 2, other_level = "Outros")

```

