---
title: "LubridateExercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
```

## Exercicios

http://material.curso-r.com/lubridate/#exerc%C3%ADcios

```{r lakers}
summary(lakers)

lakers %>% 
  mutate(asTime <- ms(time)) %>% 
  mutate(asDate <- ymd(date)) %>% 
  mutate(asDateTime <- ymd_hm(paste(date, time, sep = ""))) %>% 
  mutate(dayOfGame <- wday(ymd(date), TRUE)) %>% 
  mutate(monthOfGame <- month(ymd(date), TRUE)) %>%
  mutate(yearOfGame <- year(ymd(date)))
```

##Em média, quanto tempo o Lakers demora para arremessar a primeira bola no primeiro período?

```{r}
lakers %>% 
  filter(etype == "shot", team == "LAL", period == "1", result == "made") %>% 
  group_by(date) %>% 
  filter(time == max(time)) %>% 
  ungroup() %>% 
  summarise(meanTimeOfShot = mean(seconds(ms("12:00") - ms(time))))

```

##Quais os lances em que um arremesso foi feito com sucesso após um rebote do Pau Gasol

```{r}
#get lines from the shots
indexes2 <- which(lakers$etype=="shot" & lakers$result=="made" & dplyr::lag(lakers$etype)=="rebound" & dplyr::lag(lakers$player)=="Pau Gasol")

#get lines from the rebounds
indexes1 <- which(lakers$etype=="shot" & lakers$result=="made" & dplyr::lag(lakers$etype)=="rebound" & dplyr::lag(lakers$player)=="Pau Gasol") - 1

lakers[c(indexes1, indexes2),] %>% arrange(date, period, desc(time))

```

